version: "4.0"

actions:
  generate_measures:
    run: ehrql:v1 generate-measures analysis/dataset_definition.py --output output/measures.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/measures.csv.gz
  generate_notebook_updating_ehrql:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/sentinel_measures_updating_ehrql.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs:
      [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/sentinel_measures_updating_ehrql.html
        code_table: output/code_tabl*.csv
        charts: output/deciles_chart*.png
