
version: '4.0'

actions:

  generate_measures_alt_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_tests/measures.arrow
        --
        --test alt
    outputs:
      highly_sensitive:
        measures: output/alt_tests/measures.arrow
  generate_processed_data_alt_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/alt_tests
        --test alt
    needs:
      [generate_measures_alt_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/alt_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/alt_tests/top_5_code_table.csv
        event_counts_table: output/alt_tests/event_counts.csv


  generate_measures_chol_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/chol_tests/measures.arrow
        --
        --test chol
    outputs:
      highly_sensitive:
        measures: output/chol_tests/measures.arrow
  generate_processed_data_chol_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/chol_tests
        --test chol
    needs:
      [generate_measures_chol_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/chol_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/chol_tests/top_5_code_table.csv
        event_counts_table: output/chol_tests/event_counts.csv


  generate_measures_hba1c_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/hba1c_tests/measures.arrow
        --
        --test hba1c
    outputs:
      highly_sensitive:
        measures: output/hba1c_tests/measures.arrow
  generate_processed_data_hba1c_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/hba1c_tests
        --test hba1c
    needs:
      [generate_measures_hba1c_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/hba1c_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/hba1c_tests/top_5_code_table.csv
        event_counts_table: output/hba1c_tests/event_counts.csv


  generate_measures_rbc_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/rbc_tests/measures.arrow
        --
        --test rbc
    outputs:
      highly_sensitive:
        measures: output/rbc_tests/measures.arrow
  generate_processed_data_rbc_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/rbc_tests
        --test rbc
    needs:
      [generate_measures_rbc_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/rbc_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/rbc_tests/top_5_code_table.csv
        event_counts_table: output/rbc_tests/event_counts.csv


  generate_measures_sodium_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/sodium_tests/measures.arrow
        --
        --test sodium
    outputs:
      highly_sensitive:
        measures: output/sodium_tests/measures.arrow
  generate_processed_data_sodium_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/sodium_tests
        --test sodium
    needs:
      [generate_measures_sodium_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/sodium_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/sodium_tests/top_5_code_table.csv
        event_counts_table: output/sodium_tests/event_counts.csv


  generate_measures_systol_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/systol_tests/measures.arrow
        --
        --test systol
    outputs:
      highly_sensitive:
        measures: output/systol_tests/measures.arrow
  generate_processed_data_systol_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/systol_tests
        --test systol
    needs:
      [generate_measures_systol_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/systol_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/systol_tests/top_5_code_table.csv
        event_counts_table: output/systol_tests/event_counts.csv


  generate_measures_vit_d_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/vit_d_tests/measures.arrow
        --
        --test vit_d
    outputs:
      highly_sensitive:
        measures: output/vit_d_tests/measures.arrow
  generate_processed_data_vit_d_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/vit_d_tests
        --test vit_d
    needs:
      [generate_measures_vit_d_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/vit_d_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/vit_d_tests/top_5_code_table.csv
        event_counts_table: output/vit_d_tests/event_counts.csv


  generate_measures_vit_d_ref_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/vit_d_ref_tests/measures.arrow
        --
        --test vit_d_ref
    outputs:
      highly_sensitive:
        measures: output/vit_d_ref_tests/measures.arrow
  generate_processed_data_vit_d_ref_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/vit_d_ref_tests
        --test vit_d_ref
    needs:
      [generate_measures_vit_d_ref_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/vit_d_ref_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/vit_d_ref_tests/top_5_code_table.csv
        event_counts_table: output/vit_d_ref_tests/event_counts.csv


  generate_measures_psa_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/psa_tests/measures.arrow
        --
        --test psa
    outputs:
      highly_sensitive:
        measures: output/psa_tests/measures.arrow
  generate_processed_data_psa_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/psa_tests
        --test psa
    needs:
      [generate_measures_psa_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/psa_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/psa_tests/top_5_code_table.csv
        event_counts_table: output/psa_tests/event_counts.csv


  generate_measures_psa_ref_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/psa_ref_tests/measures.arrow
        --
        --test psa_ref
    outputs:
      highly_sensitive:
        measures: output/psa_ref_tests/measures.arrow
  generate_processed_data_psa_ref_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/psa_ref_tests
        --test psa_ref
    needs:
      [generate_measures_psa_ref_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/psa_ref_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/psa_ref_tests/top_5_code_table.csv
        event_counts_table: output/psa_ref_tests/event_counts.csv


  generate_measures_hba1c_diab_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/hba1c_diab_tests/measures.arrow
        --
        --test hba1c_diab
    outputs:
      highly_sensitive:
        measures: output/hba1c_diab_tests/measures.arrow
  generate_processed_data_hba1c_diab_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/hba1c_diab_tests
        --test hba1c_diab
    needs:
      [generate_measures_hba1c_diab_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/hba1c_diab_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/hba1c_diab_tests/top_5_code_table.csv
        event_counts_table: output/hba1c_diab_tests/event_counts.csv


  generate_measures_hba1c_diab_mean_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/hba1c_diab_mean_tests/measures.arrow
        --
        --test hba1c_diab_mean
    outputs:
      highly_sensitive:
        measures: output/hba1c_diab_mean_tests/measures.arrow
  generate_processed_data_hba1c_diab_mean_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/hba1c_diab_mean_tests
        --test hba1c_diab_mean
    needs:
      [generate_measures_hba1c_diab_mean_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/hba1c_diab_mean_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/hba1c_diab_mean_tests/top_5_code_table.csv
        event_counts_table: output/hba1c_diab_mean_tests/event_counts.csv


  generate_measures_alt_mtx_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_mtx_tests/measures.arrow
        --
        --test alt_mtx
    outputs:
      highly_sensitive:
        measures: output/alt_mtx_tests/measures.arrow
  generate_processed_data_alt_mtx_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/alt_mtx_tests
        --test alt_mtx
    needs:
      [generate_measures_alt_mtx_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/alt_mtx_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/alt_mtx_tests/top_5_code_table.csv
        event_counts_table: output/alt_mtx_tests/event_counts.csv


  generate_measures_alt_mtx_ref_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_mtx_ref_tests/measures.arrow
        --
        --test alt_mtx_ref
    outputs:
      highly_sensitive:
        measures: output/alt_mtx_ref_tests/measures.arrow
  generate_processed_data_alt_mtx_ref_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/alt_mtx_ref_tests
        --test alt_mtx_ref
    needs:
      [generate_measures_alt_mtx_ref_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/alt_mtx_ref_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/alt_mtx_ref_tests/top_5_code_table.csv
        event_counts_table: output/alt_mtx_ref_tests/event_counts.csv

