version: "4.0"

actions:
  generate_measures_alt_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_tests/measures.arrow
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      highly_sensitive:
        measures: output/alt_tests/measures.arrow
  generate_processed_data_alt_tests:
    run: >
      python:latest 
        analysis/write_processed_csv_files.py
        --output-dir output/alt_tests
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    needs:
      [generate_measures_alt_tests]
    outputs:
      moderately_sensitive:
        decile_table: output/alt_tests/deciles_table_counts_per_week_per_practice.csv
        code_table: output/alt_tests/top_5_code_table.csv
        event_counts_table: output/alt_tests/event_counts.csv
  generate_sdr_measures_alt:
    run: >
      ehrql:v1 generate-measures
        sdr/measures-definition.py
        --output output/sdr/measures_alt.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      moderately_sensitive:
        measures: output/sdr/measures_alt.csv
  generate_sdr_measures_chol:
    run: >
      ehrql:v1 generate-measures
        sdr/measures-definition.py
        --output output/sdr/measures_chol.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
    outputs:
      moderately_sensitive:
        measures: output/sdr/measures_chol.csv
  generate_sdr_measures_hba1c:
    run: >
      ehrql:v1 generate-measures
        sdr/measures-definition.py
        --output output/sdr/measures_hba1c.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
    outputs:
      moderately_sensitive:
        measures: output/sdr/measures_hba1c.csv
  generate_sdr_measures_rbc:
    run: >
      ehrql:v1 generate-measures
        sdr/measures-definition.py
        --output output/sdr/measures_rbc.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
    outputs:
      moderately_sensitive:
        measures: output/sdr/measures_rbc.csv
  generate_sdr_measures_sbp:
    run: >
      ehrql:v1 generate-measures
        sdr/measures-definition.py
        --output output/sdr/measures_sbp.csv
        --
        --codelist codelists/opensafely-systolic-blood-pressure-qof.csv
    outputs:
      moderately_sensitive:
        measures: output/sdr/measures_sbp.csv
  # Runs test to ensure correctness of measures queries
  generate_test_data:
    run: >
      ehrql:v1 generate-dataset sdr/dataset.py 
      --output output/sdr/test.csv 
      --test-data-file sdr/test_dataset.py
      --
      --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      moderately_sensitive:
        dataset: output/sdr/test.csv
