version: "4.0"

actions:
  generate_measures_alt_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_tests/measures.arrow
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      highly_sensitive:
        measures: output/alt_tests/measures.arrow
