version: "4.0"

actions:
  generate_measures:
    run: ehrql:v1 generate-measures analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
