version: "4.0"

actions:
  generate_measures_alt_tests:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/alt_tests/measures.arrow
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      highly_sensitive:
        measures: output/alt_tests/measures.arrow
  generate_processed_data:
    run: python:latest analysis/processing.py
    needs:
      [generate_measures]
    outputs:
      moderately_sensitive:
        decile_table: output/decile_tabl*.csv
        code_table: output/code_tabl*.csv
        charts: output/deciles_chart*.png