name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test_runner:
    uses: ./.github/workflows/test_runner.yaml

  deploy:
    needs: test_runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: digitalocean/app_action/deploy@cc55bc9b848d25f9c1c9f831cf843fbab3fbfb15
        with:
          token: ${{ secrets.DIGITALOCEAN_DEPLOYMENT }}
          print_build_logs: true
          print_deploy_logs: true
